#로그인 API 설정
spring:
  security:
    oauth2:
      client:
        #registration
        registration:
          #구글
          google:
            client-id: 250940130904-2m46pg67t4scd4560jqibvi68i074105.apps.googleusercontent.com
            client-secret: etIdgXd2s2y8y88OxbMxZIZa
            scope:
              - profile
              - email
          #네이버
          naver:
            client-id: D22Z3nvZT5kwK0jTedni
            client-secret: oS9kkWDPm5
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          #카카오
          kakao:
            client-id: 9bca76922d658bdbeee6cbc74851bf86
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope:
              - profile
              - account_email
            client-name: Kakao
        #provider
        provider:
          #네이버
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          #카카오
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: kakao_account